
name: ubuntu-make

# Run on every branch
on:
  push:
    branches:
    - master
    
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
        channel: 'any'

    - run: flutter --version

    - name: Get flutter dependencies
      run: flutter pub get

    # Build linux app

    - name: Get linux deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev

    - name: Allow linux desktop
      run: flutter config --enable-linux-desktop
    
    - name: Build app finally!! ^_^
      run: flutter build linux
    
    - uses: actions/upload-artifact@v2
      with:
        name: release linux binary
        path: build/linux/x64/release/bundle/
